### ISSUE TITLE
PyICU 2.0.4 fails to build with icu-62.1

### ISSUE THREAD

**Issue by gcsideal** [ovalhub/pyicu#87]
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-rHYsq1/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c _icu.cpp -o build/temp.linux-x86_64-2.7/_icu.o -DPYICU_VER="2.0.4" -std=c++11 -I/usr/include
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
_icu.cpp:53:10: fatal error: casemap.h: No such file or directory
 #include "casemap.h"
          ^~~~~~~~~~~
compilation terminated.

Indeed, the tarball available from https://pypi.org/project/PyICU/ doesn't contains the casemap.h file, but Git repository does.
Also please tag releases. That would help me a lot.

**Comment by cgohlke** [comment]
Fixed by https://github.com/ovalhub/pyicu/pull/85

**Comment by ovalhub** [comment]
fixed just now in PyICU 2.0.5

**Comment by ovalhub** [comment]
On Fri, 3 Aug 2018, László Böszörményi wrote:

> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-rHYsq1/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c _icu.cpp -o build/temp.linux-x86_64-2.7/_icu.o -DPYICU_VER="2.0.4" -std=c++11 -I/usr/include
> cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
> _icu.cpp:53:10: fatal error: casemap.h: No such file or directory
> #include "casemap.h"
>          ^~~~~~~~~~~
> compilation terminated.
>
> Indeed, the tarball available from https://pypi.org/project/PyICU/ doesn't contains the casemap.h file, but Git repository does.
> Also please tag releases. That would help me a lot.

I just release 2.0.5 which fixes several such build errors.
How does one tag a release via svn on github ?

Andi..

**Comment by gcsideal** [comment]
Indeed, it compiles now. About your question, I don't use Subversion for Git. But I think "git svn branch --tag" or its equivalent "git svn tag" is what you are looking for.
