### ISSUE TITLE
measureunit.cpp:2017:42: error: ‘t_measureunit_str’ was not declared in this scope

### ISSUE THREAD

**Issue by jwilk** [ovalhub/pyicu#67]
PyICU 2.0.1 fails to build on Ubuntu 14.04 LTS (Trusty Tahr):

```
Building PyICU 2.0.1 for ICU 52.1

Adding CXXFLAGS="-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -W -Wall -pedantic -Wpointer-arith -Wwrite-strings -Wno-long-long --std=c++0x    -D_FORTIFY_SOURCE=2 -D_REENTRANT  -DU_HAVE_ELF_H=1 -DU_HAVE_ATOMIC=1   -I/usr/include" from /usr/bin/icu-config
Adding LDFLAGS="-Wl,-Bsymbolic-functions -Wl,-z,relro  -ldl -lm   -L/usr/lib/i386-linux-gnu -licui18n -licuuc -licudata  -ldl -lm" from /usr/bin/icu-config
...
i686-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c measureunit.cpp -o build/temp.linux-i686-2.7/measureunit.o -DPYICU_VER="2.0.1" -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -W -Wall -pedantic -Wpointer-arith -Wwrite-strings -Wno-long-long --std=c++0x -D_FORTIFY_SOURCE=2 -D_REENTRANT -DU_HAVE_ELF_H=1 -DU_HAVE_ATOMIC=1 -I/usr/include
...
measureunit.cpp: In function ‘void _init_measureunit(PyObject*)’:
measureunit.cpp:2017:42: error: ‘t_measureunit_str’ was not declared in this scope
     MeasureUnitType_.tp_str = (reprfunc) t_measureunit_str;
                                          ^
error: command 'i686-linux-gnu-gcc' failed with exit status 1
```

Full build log: https://gist.github.com/anonymous/8fe4aec7166c00012ff565e596422cc6

**Comment by ovalhub** [comment]
On Sun, 14 Jan 2018, Jakub Wilk wrote:

> PyICU 2.0.1 fails to build on Ubuntu 14.04 LTS (Trusty Tahr):
>
> ```
> Building PyICU 2.0.1 for ICU 52.1
>
> Adding CXXFLAGS="-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -W -Wall -pedantic -Wpointer-arith -Wwrite-strings -Wno-long-long --std=c++0x    -D_FORTIFY_SOURCE=2 -D_REENTRANT  -DU_HAVE_ELF_H=1 -DU_HAVE_ATOMIC=1   -I/usr/include" from /usr/bin/icu-config
> Adding LDFLAGS="-Wl,-Bsymbolic-functions -Wl,-z,relro  -ldl -lm   -L/usr/lib/i386-linux-gnu -licui18n -licuuc -licudata  -ldl -lm" from /usr/bin/icu-config
> ...
> i686-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c measureunit.cpp -o build/temp.linux-i686-2.7/measureunit.o -DPYICU_VER="2.0.1" -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -W -Wall -pedantic -Wpointer-arith -Wwrite-strings -Wno-long-long --std=c++0x -D_FORTIFY_SOURCE=2 -D_REENTRANT -DU_HAVE_ELF_H=1 -DU_HAVE_ATOMIC=1 -I/usr/include
> ...
> measureunit.cpp: In function ?void _init_measureunit(PyObject*)?:
> measureunit.cpp:2017:42: error: ?t_measureunit_str? was not declared in this scope
>     MeasureUnitType_.tp_str = (reprfunc) t_measureunit_str;
>                                          ^
> error: command 'i686-linux-gnu-gcc' failed with exit status 1
> ```
>
> Full build log: https://gist.github.com/anonymous/8fe4aec7166c00012ff565e596422cc6

The HEAD revision now has a fix for this error.
Could you please try to build from it to see if other such errors are still
lurking ?

Thanks !

Andi..

**Comment by jwilk** [comment]
86fa45a417198a0e98f7fa0175c49277f414b07f builds successfully. Thanks!

**Comment by ovalhub** [comment]
All right, I’ll release 2.0.2 shortly.
Thank you !

Andi..
