### ISSUE TITLE
PyICU 2.0.4 fails to build with icu-58.2

### ISSUE THREAD

**Issue by cgohlke** [ovalhub/pyicu#86]
```
char.cpp(1394) : error C2065: 'U_WB_WSEGSPACE' : undeclared identifier
```

**Comment by ovalhub** [comment]
Indeed, that enum appeared in ICU 62

**Comment by ovalhub** [comment]
fixed

**Comment by ovalhub** [comment]
released PyICU 2.0.5 to PyPI

**Comment by cgohlke** [comment]
> released PyICU 2.0.5 to PyPI

Thank you. It works well.
